### ISSUE TITLE
Create Readme

### ISSUE THREAD

**Issue by sourabhaa** [sugarlabs/yupana#7]

**Comment by S-kus** [comment]
Hey @sourabhaa, I would like to work on this. Can I work by taking references from https://wiki.sugarlabs.org/go/Activities/Yupana#How_to_use_the_Yupana?

**Comment by quozl** [comment]
Yes.

Please also review the README.md files for the core activities to get
an idea for the format and content needed.  The core activities are
also called "sucrose".

**Comment by S-kus** [comment]
Thank You @quozl. I will take references from other README.nd.

**Comment by S-kus** [comment]
@quozl Please review the file. If any changes are in it required I will fix them.
