### ISSUE TITLE
README references Python 2 activity library

### ISSUE THREAD

**Issue by quozl** [sugarlabs/yupana#9]
The README refers to the Python 2 activity library instead of the Python 3 activity library.

https://v4.activities.sugarlabs.org/?q=yupana
https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md#checklist---maintainer

**Comment by S-kus** [comment]
@quozl Can I work on it by changing the URLs in line 28 of [Readme.md](https://github.com/sugarlabs/yupana/blob/master/README.md?plain=1).

**Comment by quozl** [comment]
I don't understand what is behind your question.  It seems very obvious.  I must be missing something.  You don't need permission.  Your next step ought to have been a pull request.  :grin:
